language: generic

osx_image: xcode9.1

branches:
  only:
  - release

env:
    global:
        - PYMODULE=pulsar
        - WHEEL=macosx

matrix:
    fast_finish: true

    include:
        - os: osx
          env: PYTHON_VERSION=3.5.4

        - os: osx
          env: PYTHON_VERSION=3.6.3

        - os: osx
          env: PYTHON_VERSION=3.7.4

        - os: osx
          env: PYTHON_VERSION=3.8.0

install:
    - ci/mac-pre-install.sh
    - source venv/bin/activate && ci/install.sh

script:
    - source venv/bin/activate && make pypi-check
    - source venv/bin/activate && make wheels-mac
    - source venv/bin/activate && make wheels-upload
